server:
    port: 1111
spring:
    application:
        name: student-service
    cloud:
        config:
            enabled: true
            uri: http://localhost:9296
    zipkin:
        base-url: http://127.0.0.1:9411