server:
  port: 9296

eureka:
  client:
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/botsteve/config-server-micro
          default-label: main